class AR {
  static const Map<String, String> arabic = {
    "buttonSkip":"تخطي >>",
    "buynow":"اشتري الآن",
    "login":"تسجيل الدخول",
    "phonenumber":"رقم التليفون",
    "password":"كلمة المرور",
    "createnewaccount":"انشاء حساب جديد",
    "nothaveaccount":"ليس لديك حساب",
    "Browsevisitor":"تصفح كزائر",
    "addCart":"أضف إلى السلة",
    "shoppingcart":"عربة التسوق",
    "bestSeller":"الأكثر مبيعا",
    "showall":"عرض الكل",
    "all":"الجميع",
    "offers":"عروض",
    "srkg":"ريال للكيلو",
    "sr":"ريال سعودى",
    "notification":"إشعار",
    "search":"عما تبحث",
    "freedelivery":"تهانينا ، لقد حصلت على توصيل مجاني",
    "confirm":"يتأكد",
    "discountcode":"كود الخصم الخاص بك",
    "noproductcart":"لا يوجد منتجات في عربة التسوق",
    "total":"مجموع",
    "DeliveryCharge":"رسوم التوصيل",
    "Totalincludingtax":"الإجمالي شاملاً الضريبة",
    "Confirmationandpayment":"التأكيد والدفع",
    "DeliveryAddress":"عنوان التسليم",
    "addnewaddress":"أضف عنوان جديد",
    "paymentmethod":"طريقة الدفع او السداد",
    "deliveryTime":"موعد التسليم",
    "confirmOrder":"أكد الطلب",
    "orders":"الطلب #٪ s",
    "tax":"ضريبة",
    "discound":"صوت",
    "confrim":"يتأكد",
    "ordersuccess":"طلب النجاح",
    "ordersuccesstext":"تتم معالجة طلبك وتسليمه في أقرب وقت ممكن. يمكنك التحقق من طلباتك الحالية أو متابعة التسوق",
    "continueshopping":"مواصلة التسوق",
    "myOrders":"طلباتي",
    "current":"الحالي",
    "theold":"القديم",
    "delivered":"تم التوصيل",
    "cart":"عربة التسوق",
    "profile":"حسابي ",
    "home":"الصفحة الرئيسية",
    "changeaddress":"تغيير العنوان",
    "profileinfo":"معلومات الملف الشخصي",
    "setting":"الاعدادات",
    "helpcenter":"مركز المساعدة",
    "aboutus":"معلومات عنا",
    "shareapp":"شارك التطبيق",
    "logout":"تسجيل خروج",
    "language":"لغة",
    "notificationsound":"صوت الإشعار",
    "facebook":"فيسبوك",
    "twiter":"تويتر",
    "snapchat":"سناب شات",
    "email":"بريد إلكتروني",
    "name":"اسم",
    "gender":"النوع",
    "male":"ذكر",
    "female":"أنثى",
    "profilesetting":"الاعدادات"
  };
}
