class EN {
  static const Map<String, String> english = {
    "buttonSkip":"Skip >>",
    "buynow":"Buy Now",
    "login":"Login",
    "phonenumber":"Phone Number",
    "password":"Password",
    "createnewaccount":"Create New Account",
    "nothaveaccount":"Not Have Account",
    "Browsevisitor":"Browse as a visitor",
    "addCart":"Add To Cart",
    "shoppingcart":"Shopping Cart",
    "bestSeller":"Best Seller",
    "showall":"Show All",
    "all":"All",
    'offers':"Offers",
    "srkg":"SR Per Kilo",
    "sr":"SR",
    "notification":"Notification",
    "search":"what are you looking for",
    "freedelivery":"Congratulations, you got free delivery",
    "confirm":"Confirm",
    "discountcode":"Your discount code",
    "noproductcart":"No Product In Shopping Cart",
    "total":"Total",
    "DeliveryCharge":"Delivery Charge",
    "Totalincludingtax":"Total including tax",
    "Confirmationandpayment":"Confirmation and payment",
    "DeliveryAddress":"Delivery Address",
    "addnewaddress":"Add New Address",
    "paymentmethod":"Payment Method",
    "deliveryTime":"Delivery Time",
    "confirmOrder":"Confirm Order",
    "orders":"Orders",
    "tax":"Tax",
    "discound":"Discound",
    "confrim":"Confirm",
    "ordersuccess":"Order Success",
    "ordersuccesstext":"Your order is being processed and delivered as soon as possible. You can check your current orders or continue shopping",
    "continueshopping":"Continue shopping",
    "myOrders":"My Orders",
    "current":"The Current",
    "theold":"The Old",
    "delivered":"Delivered",
    "cart":"Cart",
    "profile":"Profile",
    "home":"Home",
    "changeaddress":"Change Address",
    "profileinfo":"Profile  Information",
    "setting":"Setting",
    "helpcenter":"Help Center",
    "aboutus":"About Us",
    "shareapp":"Share App",
    "logout":"Logout",
    "language":"Language",
    "notificationsound":"Notification Sound",
    "facebook":"FaceBook",
    "twiter":"Twiter",
    "snapchat":"Snap Chat",
    "email":"Email",
    "name":"Name",
    "gender":"Gender",
    "male":"Male",
    "female":"Female",
    "profilesetting":"Profile Setting"
  };
}
